### ISSUE TITLE
Pio tries to compile files specifically excluded in src_filter

### ISSUE THREAD

**Issue by ASL07** [platformio/platformio-core#3506]
### Configuration

**Operating system**: OS X

**PlatformIO Version** (`platformio --version`): 4.3.3

### Description of problem
Platformio is trying to compile a library which is not included anywhere
Please see relevant parts of my folder structure:
I am compiling this library:
![image](https://user-images.githubusercontent.com/4049435/81582582-826e1100-93b0-11ea-9f09-eec641d0b04d.png)

This is the library.json content:
```
"export": {
        "exclude":
        [
            "src/iplace-common/extern/cpplogger/tests/*",
            "src/iplace-common/extern/cpplogger/build/*",
            "src/iplace-common/extern/etl/examples/*",
            "src/iplace-common/extern/etl/test/*",
            "src/iplace-common/extern/conectino/tests/**"
        ]
    },
    "build": {
        "flags":
        [
            "-Isrc/iplace-admin/include",
            "-Isrc/iplace-client/include",
            "-Isrc/iplace-common/include",
            "-Isrc/iplace-common/include/iplace-common/etl",
            "-Isrc/iplace-common/extern/etl/include",
            "-Isrc/iplace-common/extern/cpplogger/include",
            "-Isrc/iplace-device/include",
            "-Isrc/iplace-net/include",
            "-D __IPLACE_CONTROLLER_VERSION_MAJOR__=2",
            "-D __IPLACE_CONTROLLER_VERSION_MINOR__=2",
            "-D __IPLACE_CONTROLLER_VERSION_REVISION__=0"
        ], 
        "extraScript": "extra_script.py"
    },
    "frameworks": "*",
    "platforms": "*",
    "dependencies": [
        {
            "name": "FlashStorage"
        }
    ],
    "libLDFMode": "deep+"
```

This is extra_script content. Please see that iplace-common/conectino sources are excluded `"-<iplace-common/extern/conectino/src/**>"and` only included if "__BOARD_PRODINO_GPRS__" is defined:
```
Import('env')
from os.path import join, realpath, dirname

# pass flags to a global build environment (for all libraries, etc)
global_env = DefaultEnvironment()
script_dir = dirname(realpath('__file__'))

# private library flags
env.Replace(SRC_FILTER=[
    "+<*>",
    "-<**/example/**>",
    "-<**/examples/**>",
    "-<**/test/**>",
    "-<**/tests/**>",

    # Exclude HW dependent sources which will be included depending on environment
    "-<iplace-net/src/esp8266/**>",
    "-<iplace-device/src/esp8266-common/**>",
    "-<iplace-device/src/sonoff/**>",
    "-<iplace-device/src/olimex_esp8266_evb/**>",
    "-<iplace-device/src/prodino_gprs/**>",

    # Exclude conectino
    "-<iplace-common/extern/conectino/src/**>",
])

for item in env.get("CPPDEFINES", []):
    # PLATFORM
    if "__PLATFORM_ARDUINO__" in item:
        env.Append(SRC_FILTER=[
            "+<iplace-device/src/arduino-common/src/*>"
        ])
        env.Append(CPPPATH=[
            join(script_dir, "src/iplace-device/src/arduino-common/include")
        ]) 
    
    # FRAMEWORK
    if "__FRAMEWORK_ESP8266__" in item:
        env.Append(SRC_FILTER=[
            "+<iplace-net/src/esp8266/src/*>"
        ])
        env.Append(CPPPATH=[
            join(script_dir, "src/iplace-net/src/esp8266/include")
        ])

    # BOARD
    if "__BOARD_SONOFF_MINI__" in item:
        env.Append(SRC_FILTER=[
            "+<iplace-device/src/sonoff/src/*>",
            "+<iplace-device/src/esp8266-common/src/*>"
        ])
        env.Append(CPPPATH=[
            join(script_dir, "src/iplace-device/src/sonoff/include"),
            join(script_dir, "src/iplace-device/src/esp8266-common/include")
        ])
    if "__BOARD_OLIMEX_ESP8266_EVB__" in item:
        env.Append(SRC_FILTER=[
            "+<iplace-device/src/olimex_esp8266_evb/src/*>",
            "+<iplace-device/src/esp8266-common/src/*>"
        ])
        env.Append(CPPPATH=[
            join(script_dir, "src/iplace-device/src/olimex_esp8266_evb/include"),
            join(script_dir, "src/iplace-device/src/esp8266-common/include")
        ])
    if "__BOARD_PRODINO_GPRS__" in item:
        env.Append(CPPDEFINES=[
            "-D __MODEM_SARA_U201"
        ])
        env.Append(SRC_FILTER=[
            "+<iplace-device/src/prodino_gprs/src/*>",
            "+<iplace-net/src/sara_u201/src/*>",

            "+<iplace-common/extern/conectino/common/**",
            "+<iplace-common/extern/conectino/modem/**",
            "+<iplace-common/extern/conectino/utils/**",
            "+<iplace-common/extern/conectino/src/modem_drv/drv_sara_u201.cpp>",
        ])
        env.Append(CPPPATH=[
            join(script_dir, "src/iplace-device/src/prodino_gprs/include"),
            join(script_dir, "src/iplace-net/src/sara_u201/include"),

            join(script_dir, "iplace-common/extern/conectino/common/include"),
            join(script_dir, "iplace-common/extern/conectino/modem/include"),
            join(script_dir, "iplace-common/extern/conectino/utils/include"),
            join(script_dir, "iplace-common/extern/conectino/src/modem-drv/include"),
        ])

# Print environment for debugging
print(env.Dump())

print(env.get("CPPDEFINES", []))

```

![image](https://user-images.githubusercontent.com/4049435/81582467-62d6e880-93b0-11ea-9ab2-996580b86d0c.png)

This is the content of platformio.ini
```
[env]
monitor_speed = 115200
upload_port = /dev/tty.usbserial-A50285BI
lib_extra_dirs = /Users/developer/Code/common
lib_ldf_mode = deep+
lib_deps =
    DallasTemperature
    OneWire
    IplaceController

#####   Olimex Esp8266 evb   #####
[env:olimex_esp8266_evb]
platform = espressif8266
board = modwifi
framework = arduino
src_filter =
    -<*>
    +<main_olimex_esp8266_evb.cpp>
build_flags =   
    -D__PLATFORM_ARDUINO__
    -D__FRAMEWORK_ESP8266__
    -D__BOARD_OLIMEX_ESP8266_EVB__

#####   Prodino GPRS  #####
[env:prodino_gprs]
platform = atmelsam
board = mkrgsm1400
framework = arduino
debug_tool = jlink
debug_load_mode = modified
; debug_init_break = break setup
; SWD interface
upload_protocol = jlink
build_flags = 
    -D__PLATFORM_ARDUINO__
    -D__FRAMEWORK_SAMD21__
    -D__BOARD_PRODINO_GPRS__
src_filter =
    -<*>
    +<main_prodino_gprs.cpp>
```

Expected:
When I compile environment olimex_esp8266_evb, then conectino sources are not included

Actual:
When I compile olimex_esp8266_evb conectino sources are included. Please see output of pio run:
```
[('PLATFORMIO', 40303), 'ESP8266', 'ARDUINO_ARCH_ESP8266', 'ARDUINO_MOD_WIFI_ESP8266', '__PLATFORM_ARDUINO__', '__FRAMEWORK_ESP8266__', '__BOARD_OLIMEX_ESP8266_EVB__', ('F_CPU', '$BOARD_F_CPU'), '__ets__', 'ICACHE_FLASH', ('ARDUINO', 10805), ('ARDUINO_BOARD', '\\"PLATFORMIO_MODWIFI\\"'), 'FLASHMODE_${BOARD_FLASH_MODE.upper()}', 'LWIP_OPEN_SRC', ('NONOSDK22x_190703', 1), ('TCP_MSS', 536), ('LWIP_FEATURES', 1), ('LWIP_IPV6', 0), 'VTABLES_IN_FLASH', ('__IPLACE_CONTROLLER_VERSION_MAJOR__', 2), ('__IPLACE_CONTROLLER_VERSION_MINOR__', 2), ('__IPLACE_CONTROLLER_VERSION_REVISION__', 0)]
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <DallasTemperature> 3.8.1
|   |-- <OneWire> 2.3.5
|-- <OneWire> 2.3.5
|-- <IplaceController> 1.0.0
|   |-- <EEPROM> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |   |-- <Conectino> 0.1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |   |-- <Conectino> 0.1.0
|   |-- <ESP8266HTTPUpdateServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |   |-- <Conectino> 0.1.0
|   |   |-- <ESP8266WebServer> 1.0
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |   |   |-- <Conectino> 0.1.0
|   |-- <DallasTemperature> 3.8.1
|   |   |-- <OneWire> 2.3.5
|   |-- <OneWire> 2.3.5
|   |-- <Ticker> 1.0
|   |-- <Conectino> 0.1.0
|-- <ESP8266WiFi> 1.0
|   |-- <Conectino> 0.1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |   |-- <Conectino> 0.1.0
|-- <ESP8266HTTPUpdateServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |   |-- <Conectino> 0.1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |   |-- <Conectino> 0.1.0
|-- <EEPROM> 1.0
Building in release mode
Archiving .pio/build/olimex_esp8266_evb/lib07c/libDallasTemperature_ID54.a
Indexing .pio/build/olimex_esp8266_evb/lib07c/libDallasTemperature_ID54.a
Compiling .pio/build/olimex_esp8266_evb/lib714/conectinolibrary/common/cn_tcp.cpp.o
Compiling .pio/build/olimex_esp8266_evb/lib714/conectinolibrary/common/cn_udp.cpp.o
Compiling .pio/build/olimex_esp8266_evb/lib714/conectinolibrary/modem/cn_modem.cpp.o
Compiling .pio/build/olimex_esp8266_evb/lib714/conectinolibrary/utils/cn_logger.cpp.o
/Users/developer/Code/common/conectinolibrary/src/modem/cn_modem.cpp: In member function 'virtual void Conectuino::Modem::poll()':
/Users/developer/Code/common/conectinolibrary/src/modem/cn_modem.cpp:292:31: warning: unused variable 'urc_end' [-Wunused-variable]
                         char* urc_end = strstr(_buffer, get_rsp_terminator()) + strlen(get_rsp_terminator());        
                               ^
/Users/developer/Code/common/conectinolibrary/src/common/cn_udp.cpp: In member function 'bool Conectuino::Udp::is_duplicate(uint8_t*, size_t)':
/Users/developer/Code/common/conectinolibrary/src/common/cn_udp.cpp:275:64: error: 'mem_in_mem' was not declared in this scope
     if (mem_in_mem(rx_buf, rx_bytes, new_packet, new_packet_len))
                                                                ^
/Users/developer/Code/common/conectinolibrary/src/common/cn_tcp.cpp: In member function 'bool Conectuino::Tcp::is_duplicate(uint8_t*, size_t)':
/Users/developer/Code/common/conectinolibrary/src/common/cn_tcp.cpp:340:64: error: 'mem_in_mem' was not declared in this scope
     if (mem_in_mem(rx_buf, rx_bytes, new_packet, new_packet_len))
                                                                ^
*** [.pio/build/olimex_esp8266_evb/lib714/conectinolibrary/common/cn_udp.cpp.o] Error 1
*** [.pio/build/olimex_esp8266_evb/lib714/conectinolibrary/common/cn_tcp.cpp.o] Error 1
```

It is really strange that conectino is listed as a dependency of ESP8266WiFi , which is an Arduino core library

Do you have any suggestions? Is there any way to get more information about where specific files/libraries are added to the build

**Comment by valeros** [comment]
Hi @ASL07 ! Is there a repository for your project or maybe you can upload it somewhere?

**Comment by ASL07** [comment]
Hi @valeros, I have added you as collaborator to one of the projects where I am having the same issue.
Please see details on the repository readme
Thank you

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platformio-core/commit/0eb8895959c90cda07f014294d854cf76913c0d7

Looks like the recursive `**` pattern wasn't fully supported. Please retest with the latest platformio-core from the development branch. Keep in mind that only Python 3 supports this feature.

**Comment by ASL07** [comment]
I have updated to the last dev branch and I still face the issue.
The recursive glob expressions work for me in the main project's platformmio.ini, but they don't work for libraries (when using glob expressions inside librarty.json or in the library extra_script)

**Comment by valeros** [comment]
That's strange. I tested it on your project `modbus` and it works as expected. What OS do you use?

**Comment by ASL07** [comment]
I am using Os X and Python 3.7.7. 
Have retested again using the repo modbus and I am experiencing the same issue

**Comment by valeros** [comment]
Looks like we're testing different things. Could you please try to compile the following basic project with your library specified as a dependency: [test-recursive.zip](https://github.com/platformio/platformio-core/files/4711509/test-recursive.zip)

**Comment by valeros** [comment]
Hi @ASL07 ! Any updates on the issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
